# -*- mode: ruby -*-
# vi: set ft=ruby  :

Vagrant.configure("2") do |config|
	config.vm.define "Prometheus" do |prometheus|
		prometheus.vm.box = "ubuntu/focal64"
		prometheus.vm.hostname = "Prometheus.marcelobreda.local"
		prometheus.vm.network "public_network", bridge: "wlp6s0",ip: "192.168.0.60"
		prometheus.vm.provider "virtualbox" do |vb|
			vb.name = "Prometheus"
			vb.memory = 2048
			vb.cpus = 2
		end
		prometheus.vm.provision "shell", path:"./scripts/prometheus.sh"
		
	end		
	
	
end
